### ISSUE TITLE
to-do list:

### ISSUE THREAD

**Issue by konstantinosKokos** [konstantinosKokos/CRA#1]
- [ ] Check the graph
 - [x] Add the graph to .tex and beautify
 - [x] Expand paragraph about strict rules?
 - [x] Write some conclusions on the argument dynamics 
 - [ ] Final proof-reading and corrections
 - [ ]  SUPER IMPORTANT: Make sure toast link is correct
